fixed undefined reference to _write on Teensy31 boards (#397) (#398)
(cherry picked from commit 541e7e7d49c2ba83b0d291879cf1b888463dafa9)

Co-authored-by: Juan Miguel Jimeno <jimenojmm@gmail.com>