fixed undefined reference to _write on Teensy 3.6 (#388) (#389)
* fixed undefined reference to _write on Teensy 3.6

* added Teeny 3.6 on supported boards

(cherry picked from commit da05e6bb06bdfe7a0c9eaa458ce726ae242e66f6)

Co-authored-by: Juan Miguel Jimeno <jimenojmm@gmail.com>